datasets:
  ch_sims_v2_s_ft:
    data_type: images
    build_info:
      image_path: /home/user/big_space/datasets/Emotion/CH-SIMS_v2_s/video
      ann_path: /home/user/big_space/datasets/Emotion/AU_gpt/CH-SIMS_v2_s_AU_gpt.csv