datasets:
  dfew_ft:
    data_type: images
    build_info:
      image_path: /home/user/big_space/datasets/Emotion/DFEW/video
      ann_path: /home/user/big_space/datasets/Emotion/AU_gpt/DFEW_AU_gpt.csv