datasets:
  mer2024_semi:
    data_type: images
    build_info:
      image_path: /home/user/big_space/datasets/Emotion/MER2024/video
      ann_path: /home/user/big_space/datasets/Emotion/MER2024/MER2024_merged.csv